# coding: utf-8

"""
    VPlex REST API

    A defnition for the next-gen VPlex API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JobsStoragePools(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'storage_pool': 'str',
        'storage_group': 'str'
    }

    attribute_map = {
        'storage_pool': 'storage_pool',
        'storage_group': 'storage_group'
    }

    def __init__(self, storage_pool=None, storage_group=None):  # noqa: E501
        """JobsStoragePools - a model defined in Swagger"""  # noqa: E501

        self._storage_pool = None
        self._storage_group = None
        self.discriminator = None

        if storage_pool is not None:
            self.storage_pool = storage_pool
        if storage_group is not None:
            self.storage_group = storage_group

    @property
    def storage_pool(self):
        """Gets the storage_pool of this JobsStoragePools.  # noqa: E501

        Which pool to provision the underlying storage from.   # noqa: E501

        :return: The storage_pool of this JobsStoragePools.  # noqa: E501
        :rtype: str
        """
        return self._storage_pool

    @storage_pool.setter
    def storage_pool(self, storage_pool):
        """Sets the storage_pool of this JobsStoragePools.

        Which pool to provision the underlying storage from.   # noqa: E501

        :param storage_pool: The storage_pool of this JobsStoragePools.  # noqa: E501
        :type: str
        """

        self._storage_pool = storage_pool

    @property
    def storage_group(self):
        """Gets the storage_group of this JobsStoragePools.  # noqa: E501

        Which storage group to use. If omitted, storage group is assigned automatically.   # noqa: E501

        :return: The storage_group of this JobsStoragePools.  # noqa: E501
        :rtype: str
        """
        return self._storage_group

    @storage_group.setter
    def storage_group(self, storage_group):
        """Sets the storage_group of this JobsStoragePools.

        Which storage group to use. If omitted, storage group is assigned automatically.   # noqa: E501

        :param storage_group: The storage_group of this JobsStoragePools.  # noqa: E501
        :type: str
        """

        self._storage_group = storage_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsStoragePools):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
