# coding: utf-8

"""
    VPlex REST API

    A defnition for the next-gen VPlex API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JsonPatchOp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'op': 'str',
        'path': 'str',
        'value': 'object'
    }

    attribute_map = {
        'op': 'op',
        'path': 'path',
        'value': 'value'
    }

    def __init__(self, op=None, path=None, value=None):  # noqa: E501
        """JsonPatchOp - a model defined in Swagger"""  # noqa: E501

        self._op = None
        self._path = None
        self._value = None
        self.discriminator = None

        self.op = op
        self.path = path
        self.value = value

    @property
    def op(self):
        """Gets the op of this JsonPatchOp.  # noqa: E501

        The body of an HTTP PATCH is a Json array of JsonPatchOp objects. These patch operations are applied sequentially to the resource to which the PATCH was sent. If any operation results in a failure, execution of any subsequent operations is aborted, but no roll-back is performed.  The field the operation acts on is specified by 'path'.  Operations are applied in a consistent order, by type:   1. test - Assert that the value of a scalar-valued field is equal to 'value' at the start of the patch operation.   2. add - Insert 'value' into a collection-valued field.   3. remove  - Remove 'value' from a collection-valued field.   4. replace - Set a scalar-valued field to 'value'.  Operations of the same type are applied in the order they appear in the patch body.   # noqa: E501

        :return: The op of this JsonPatchOp.  # noqa: E501
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op):
        """Sets the op of this JsonPatchOp.

        The body of an HTTP PATCH is a Json array of JsonPatchOp objects. These patch operations are applied sequentially to the resource to which the PATCH was sent. If any operation results in a failure, execution of any subsequent operations is aborted, but no roll-back is performed.  The field the operation acts on is specified by 'path'.  Operations are applied in a consistent order, by type:   1. test - Assert that the value of a scalar-valued field is equal to 'value' at the start of the patch operation.   2. add - Insert 'value' into a collection-valued field.   3. remove  - Remove 'value' from a collection-valued field.   4. replace - Set a scalar-valued field to 'value'.  Operations of the same type are applied in the order they appear in the patch body.   # noqa: E501

        :param op: The op of this JsonPatchOp.  # noqa: E501
        :type: str
        """
        if op is None:
            raise ValueError("Invalid value for `op`, must not be `None`")  # noqa: E501
        allowed_values = ["add", "remove", "replace", "test"]  # noqa: E501
        if op not in allowed_values:
            raise ValueError(
                "Invalid value for `op` ({0}), must be one of {1}"  # noqa: E501
                .format(op, allowed_values)
            )

        self._op = op

    @property
    def path(self):
        """Gets the path of this JsonPatchOp.  # noqa: E501

        A Json pointer to the target of an operation  # noqa: E501

        :return: The path of this JsonPatchOp.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this JsonPatchOp.

        A Json pointer to the target of an operation  # noqa: E501

        :param path: The path of this JsonPatchOp.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def value(self):
        """Gets the value of this JsonPatchOp.  # noqa: E501

        The value to be used for the given operation  # noqa: E501

        :return: The value of this JsonPatchOp.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this JsonPatchOp.

        The value to be used for the given operation  # noqa: E501

        :param value: The value of this JsonPatchOp.  # noqa: E501
        :type: object
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JsonPatchOp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
