# coding: utf-8

"""
    VPlex REST API

    A defnition for the next-gen VPlex API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LoginResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'token_type': 'str',
        'expires_in': 'str'
    }

    attribute_map = {
        'token': 'token',
        'token_type': 'token_type',
        'expires_in': 'expires_in'
    }

    def __init__(self, token=None, token_type=None, expires_in=None):  # noqa: E501
        """LoginResponse - a model defined in Swagger"""  # noqa: E501

        self._token = None
        self._token_type = None
        self._expires_in = None
        self.discriminator = None

        if token is not None:
            self.token = token
        if token_type is not None:
            self.token_type = token_type
        if expires_in is not None:
            self.expires_in = expires_in

    @property
    def token(self):
        """Gets the token of this LoginResponse.  # noqa: E501

        JWT token  # noqa: E501

        :return: The token of this LoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this LoginResponse.

        JWT token  # noqa: E501

        :param token: The token of this LoginResponse.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def token_type(self):
        """Gets the token_type of this LoginResponse.  # noqa: E501

        Bearer token  # noqa: E501

        :return: The token_type of this LoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type):
        """Sets the token_type of this LoginResponse.

        Bearer token  # noqa: E501

        :param token_type: The token_type of this LoginResponse.  # noqa: E501
        :type: str
        """

        self._token_type = token_type

    @property
    def expires_in(self):
        """Gets the expires_in of this LoginResponse.  # noqa: E501

        Expiry time  # noqa: E501

        :return: The expires_in of this LoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in):
        """Sets the expires_in of this LoginResponse.

        Expiry time  # noqa: E501

        :param expires_in: The expires_in of this LoginResponse.  # noqa: E501
        :type: str
        """

        self._expires_in = expires_in

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoginResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
