# coding: utf-8

"""
    VPlex REST API

    A defnition for the next-gen VPlex API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StorageViewVirtualVolumes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uri': 'str',
        'vpd_id': 'str',
        'capacity': 'int',
        'lun': 'int'
    }

    attribute_map = {
        'uri': 'uri',
        'vpd_id': 'vpd_id',
        'capacity': 'capacity',
        'lun': 'lun'
    }

    def __init__(self, uri=None, vpd_id=None, capacity=None, lun=None):  # noqa: E501
        """StorageViewVirtualVolumes - a model defined in Swagger"""  # noqa: E501

        self._uri = None
        self._vpd_id = None
        self._capacity = None
        self._lun = None
        self.discriminator = None

        if uri is not None:
            self.uri = uri
        if vpd_id is not None:
            self.vpd_id = vpd_id
        if capacity is not None:
            self.capacity = capacity
        if lun is not None:
            self.lun = lun

    @property
    def uri(self):
        """Gets the uri of this StorageViewVirtualVolumes.  # noqa: E501


        :return: The uri of this StorageViewVirtualVolumes.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this StorageViewVirtualVolumes.


        :param uri: The uri of this StorageViewVirtualVolumes.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def vpd_id(self):
        """Gets the vpd_id of this StorageViewVirtualVolumes.  # noqa: E501


        :return: The vpd_id of this StorageViewVirtualVolumes.  # noqa: E501
        :rtype: str
        """
        return self._vpd_id

    @vpd_id.setter
    def vpd_id(self, vpd_id):
        """Sets the vpd_id of this StorageViewVirtualVolumes.


        :param vpd_id: The vpd_id of this StorageViewVirtualVolumes.  # noqa: E501
        :type: str
        """

        self._vpd_id = vpd_id

    @property
    def capacity(self):
        """Gets the capacity of this StorageViewVirtualVolumes.  # noqa: E501


        :return: The capacity of this StorageViewVirtualVolumes.  # noqa: E501
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this StorageViewVirtualVolumes.


        :param capacity: The capacity of this StorageViewVirtualVolumes.  # noqa: E501
        :type: int
        """

        self._capacity = capacity

    @property
    def lun(self):
        """Gets the lun of this StorageViewVirtualVolumes.  # noqa: E501


        :return: The lun of this StorageViewVirtualVolumes.  # noqa: E501
        :rtype: int
        """
        return self._lun

    @lun.setter
    def lun(self, lun):
        """Sets the lun of this StorageViewVirtualVolumes.


        :param lun: The lun of this StorageViewVirtualVolumes.  # noqa: E501
        :type: int
        """

        self._lun = lun

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageViewVirtualVolumes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
