# coding: utf-8

"""
    VPlex REST API

    A defnition for the next-gen VPlex API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UnclaimPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vias_return_to_pool': 'bool'
    }

    attribute_map = {
        'vias_return_to_pool': 'vias_return_to_pool'
    }

    def __init__(self, vias_return_to_pool=None):  # noqa: E501
        """UnclaimPayload - a model defined in Swagger"""  # noqa: E501

        self._vias_return_to_pool = None
        self.discriminator = None

        if vias_return_to_pool is not None:
            self.vias_return_to_pool = vias_return_to_pool

    @property
    def vias_return_to_pool(self):
        """Gets the vias_return_to_pool of this UnclaimPayload.  # noqa: E501

        For VIAS-based storage-volumes, this will return the storage capacity of each VIAS-based volume to the pool on the corresponding storage-array.   # noqa: E501

        :return: The vias_return_to_pool of this UnclaimPayload.  # noqa: E501
        :rtype: bool
        """
        return self._vias_return_to_pool

    @vias_return_to_pool.setter
    def vias_return_to_pool(self, vias_return_to_pool):
        """Sets the vias_return_to_pool of this UnclaimPayload.

        For VIAS-based storage-volumes, this will return the storage capacity of each VIAS-based volume to the pool on the corresponding storage-array.   # noqa: E501

        :param vias_return_to_pool: The vias_return_to_pool of this UnclaimPayload.  # noqa: E501
        :type: bool
        """

        self._vias_return_to_pool = vias_return_to_pool

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnclaimPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
