# coding: utf-8

"""
    VPlex REST API

    A definition for the next-gen VPlex API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SystemConfigBranding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'platform': 'str',
        'product_name': 'str'
    }

    attribute_map = {
        'platform': 'platform',
        'product_name': 'product_name'
    }

    def __init__(self, platform=None, product_name=None):  # noqa: E501
        """SystemConfigBranding - a model defined in Swagger"""  # noqa: E501

        self._platform = None
        self._product_name = None
        self.discriminator = None

        if platform is not None:
            self.platform = platform
        if product_name is not None:
            self.product_name = product_name

    @property
    def platform(self):
        """Gets the platform of this SystemConfigBranding.  # noqa: E501


        :return: The platform of this SystemConfigBranding.  # noqa: E501
        :rtype: str
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this SystemConfigBranding.


        :param platform: The platform of this SystemConfigBranding.  # noqa: E501
        :type: str
        """
        allowed_values = ["UNKNOWN", "GENERIC", "VS2", "VS6"]  # noqa: E501
        if platform not in allowed_values:
            raise ValueError(
                "Invalid value for `platform` ({0}), must be one of {1}"  # noqa: E501
                .format(platform, allowed_values)
            )

        self._platform = platform

    @property
    def product_name(self):
        """Gets the product_name of this SystemConfigBranding.  # noqa: E501


        :return: The product_name of this SystemConfigBranding.  # noqa: E501
        :rtype: str
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name):
        """Sets the product_name of this SystemConfigBranding.


        :param product_name: The product_name of this SystemConfigBranding.  # noqa: E501
        :type: str
        """

        self._product_name = product_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemConfigBranding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
